### PR TITLE
Enabling publishing of slides through github pages.

### PR DESCRIPTION
**Pull request by ashic**
* changed build to output to /docs
* updated readme

### CODE REVIEW

**Comment by julien-truffaut** [comment]
cool, you don't need to configure github pages?

**Comment by ashic** [comment]
Nope... afaik, if it's in docs in master, it's magic.

**Comment by ashic** [comment]
Takes a few minutes to kick in though.

**Comment by ashic** [comment]
My bad... it's magic if it's in root, or in gh-pages branch. You'll need to go to settings, and change it to "docs folder in master".

**Pull request merged**
